projetoCidades/Models/Cidade.cs
using System.Collections.Generic;

namespace projetoCidades.Models {
    public class Cidade {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Estado { get; set; }
        public int Habitantes { get; set; }
        public List<Cidade> ListarCidades () {
            List<Cidade> cidade = new List<Cidade> () {
                new Cidade { Id = 1, Nome = "São Paulo", Estado = "SP", Habitantes = 123412 },
                new Cidade { Id = 2, Nome = "Rio de Janeiro", Estado = "RJ", Habitantes = 123412 },
                new Cidade { Id = 3, Nome = "Porto Alegre", Estado = "RS", Habitantes = 346554 },
                new Cidade { Id = 4, Nome = "Campinas", Estado = "SP", Habitantes = 234565 },
                new Cidade { Id = 5, Nome = "Vitória", Estado = "ES", Habitantes = 1235476 },
                new Cidade { Id = 6, Nome = "Londrina", Estado = "PR", Habitantes = 1234987 }
            };
            return cidade;
        }
    }
}

projetoCidades/Models/ErrorViewModel.cs
using System;

namespace projetoCidades.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

projetoCidades/Controllers/CidadesController.cs
using Microsoft.AspNetCore.Mvc;
using projetoCidades.Models;
using projetoCidades.Repositorio;

namespace projetoCidades.Controllers {
    public class CidadesController : Controller {
        CidadeRep cidadeRep = new CidadeRep ();
        Cidade cidade = new Cidade ();
        public IActionResult Index () {
            // Execução do método LISTARCIDADES, para trazer a lista de cidades.
            var list = cidadeRep.Listar ();
            return View (list);
        }
        public IActionResult CidadesEstados () {
            var list = cidadeRep.Listar ();
            return View (list);
        }
        public IActionResult TodosOsDados () {
            var list = cidadeRep.Listar ();
            return View (list);
        }
        public IActionResult Cadastrar () {
            return View ();
        }

        // [HttpPost] é usado para receber os parametrôs de um formulário.
        // [Bind] é usado quando recebemos as informações de um formulário.
        [HttpPost]
        public IActionResult Cadastrar ([Bind] Cidade cidade) {
            cidadeRep.Cadastrar (cidade);
            return RedirectToAction("Index");
        }
    }
}

projetoCidades/Views/Cidades/Cadastrar.cshtml
@model projetoCidades.Models.Cidade

<div>
    <h2>Cadastrar</h2>
    <h4>Cidade</h4>
    <hr>
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Cadastrar">
                <div asp-validation-sumary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Nome" class="control-label">Cidade</label>
                    <input asp-for="Nome" class="form-control"/>
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Estado" class="control-label"></label>
                    <input asp-for="Estado" class="form-control"/>
                    <span asp-validation-for="Estado" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Habitantes" class="control-label"></label>
                    <input asp-for="Habitantes" class="form-control"/>
                    <span asp-validation-for="Habitantes" class="text-danger"></span>
                </div>
                <div class="form-group">
                   <button type="submit" value="Cadastrar" class="btn btn-default">Cadastrar</button>
                </div>
            </form>
        </div>
    </div>
</div>

projetoCidades/Views/Cidades/CidadesEstados.cshtml
@model IEnumerable<projetoCidades.Models.Cidade>

<div>
    @* o @ é utilizado para execução de comando RAZOR *@
    <h2>Cidades e Estados</h2>
    
        <table>
            <tr>
                <th >
                    Cidades
                </th>
                <th>
                    Estado
                </th>
            </tr>
            @{
                foreach(var item in Model) {
                    <tr>
                        <td>
                            @item.Nome
                        </td>
                        <td>
                            @item.Estado
                        </td>
                    </tr>
                }
            }
        </table>
</div>

projetoCidades/Views/Cidades/Index.cshtml
@model IEnumerable<projetoCidades.Models.Cidade>

<div>
    @* o @ é utilizado para execução de comando RAZOR *@
    <h2>Minhas cidades</h2>

    <p>
    <a asp-action="Cadastrar">Cadastrar nova cidade</a>
    </p>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Cidade</th>
                <th>Estado</th>
                <th>Habitantes</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach(var item in Model){
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Nome</td>
                        <td>@item.Estado</td>
                        <td>@item.Habitantes</td>
                        <td>
                            @* COMANDO UTILIZADO PARA DIRECIONAR O USUARIO PARA A PÁGINA "EDITAR" COM O PARAMETRO ID *@
                            <a asp-action="Editar" asp-route-id="@item.Id">Editar</a> &nbsp;&nbsp;
                            <a asp-action="Detalhes" asp-route-id="@item.Id">Detalhes</a> &nbsp; &nbsp;
                            <a asp-action="Excluir" asp-route-id="@item.Id">Excluir</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

projetoCidades/Views/Cidades/TodosOsDados.cshtml
@model IEnumerable<projetoCidades.Models.Cidade>

<div>
    @* o @ é utilizado para execução de comando RAZOR *@
    <h2>Todos os dados</h2>
    
        <table>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Cidades
                </th>
                <th>
                    Estado
                </th>
                <th>
                    Habitantes
                </th>
            </tr>
                @{
                    foreach(var item in Model) {
                        <tr>
                            <td>
                                @item.Id
                            </td>
                            <td>
                                @item.Nome
                            </td>
                            <td>
                                @item.Estado
                            </td>
                            <td>
                                @item.Habitantes
                            </td>
                        </tr>
                    }
                }
            
        </table>
</div>

projetoCidades/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - projetoCidades</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Cidades" asp-action="Index" class="navbar-brand">Projeto Cidades</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Cidades" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Cidades" asp-action="CidadesEstados">Cidades e Estados</a></li>
                    <li><a asp-area="" asp-controller="Cidades" asp-action="TodosOsDados">Todos os dados</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - projetoCidades</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>